jaffle_shop:
  target: local
  outputs:
    local:
      type: snowflake
      account: 'GP21411.us-east-1'
      user: 'CONSTANCEM'
      role: 'CONSTANCEM'

      private_key_path: '/Users/cmarteepants/snowflake_rsa_key.p8'
      private_key_passphrase: 'snowflake'

      database: 'SANDBOX'
      schema: 'CONSTANCEM'
      threads: 200
      client_session_keep_alive: False
    dev:
      type: snowflake
      account: 'GP21411.us-east-1'
      user: 'CONSTANCEM'
      role: 'CONSTANCEM'

      private_key_path: '/usr/local/airflow/snowflake_rsa_key.p8'
      private_key_passphrase: 'snowflake'

      database: 'SANDBOX'
      schema: 'CONSTANCEM'
      threads: 200
      client_session_keep_alive: False
