version: "3.1"

# mount the dbt directory as a volume
services:
  scheduler:
    volumes:
      - ../dbt:/usr/local/airflow/dbt
      - /Users/cmarteepants/snowflake_rsa_key.p8:/usr/local/airflow/snowflake_rsa_key.p8
  webserver:
    volumes:
      - ../dbt:/usr/local/airflow/dbt